# Constants

BASE_DIRECTORY="Runs_to_use"
DEPTH = 16

BATCH_SIZE = 250
TEST_BATCH_SIZE = 1000

EPOCHS = 75


MOMENTUM = 0.5
USE_CUDA = False
SEED = 1
LOG_INTERVAL = 10
SAVE_MODEL = False
LEARNING_RATE = 0.01

LOG_WHILE_TRAINING = False

DIVIDES_IN_ROW_CIFAR = 3  # RGB

DIVIDES_IN_ROW = 3
DIVIDES_IN_COL = 2
AMOUNT_OF_DIVISIONS = DIVIDES_IN_COL * DIVIDES_IN_ROW

M = 64  # Output Dimension of the feature map
RANK = 50
RANK_FIRST_AND_LAST=1

ONE = 1

FIRST = 0
SECOND = 1
THIRD = 2
LAST = -1
OUTPUT_RANK_FIRST_KERNEL = -1

ZERO_DIMENSION = 0
FIRST_DIMENSION = 1
SECOND_DIMENSION = 2
SIZE_ONE_DIMENSION = 1

BATCH_DIMENSION = 0
DIVISION_DIMENSION = 1
M_DIMENSION = 2

ADAM = "Adam"
SGD = "SGD"

MODEL_FILENAME = "model.pt"

MAX_VOCAB_SIZE = 25000

N_PARALLEL_NETS = 3

CATEGORIES = 2
CATEGORIES_MNIST = 10
CATEGORIES_CIFAR = 10
CATEGORIES_IMDB = 1

TENSOR_SIZE_CIFAR = 32 * 32 * 3
TENSOR_SIZE_CIFAR_PARALLEL = 32 * 32
TENSOR_SIZE_MNIST = 28 * 28
TENSOR_SIZE = 28 * 28
#TENSOR_SIZE_CIFAR_CNN =1000
TENSOR_SIZE_CIFAR_CNN = 256*4*4
TENSOR_SIZE_CIFAR_MNIST =640

#FIXED_LENGTH = 200  # None to void
FIXED_LENGTH = 200
EMBEDDING_DIM = 50
TENSOR_SIZE_IMDB =  EMBEDDING_DIM * FIXED_LENGTH
TENSOR_SIZE_IMDB_CONV = 300
#INIT_VALUE=1
INIT_VALUE=100

NET_PARAMETERS_INDEX = 10
NET_PARAMETERS_INDEX_WITH_DROPOUT = 11

NET_ACCURACY_INDEX = 1
NET_TYPE_INDEX = 0
NET_M_INDEX = 5
NET_RANK_INDEX = 4
EPOCH_TIME_INDEX = 13

NET_PARAMETERS_INDEX_RUN = 1

DROPOUT=0.25
